//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSP.NET_Pineda
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        public int IdCompra { get; set; }
        public Nullable<int> IdProductor { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<int> Tara { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> FactorCambioDolar { get; set; }
        public Nullable<decimal> PrecioCafe { get; set; }
        public Nullable<System.DateTime> FechaCompra { get; set; }
    
        public virtual Productores Productores { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
